# Generated by Django 4.2.2 on 2024-04-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_subjects_division_remove_subjects_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='batch',
            field=models.ManyToManyField(related_name='teachers_batch', to='users.batch'),
        ),
    ]
