# Generated by Django 4.2.2 on 2024-04-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teacherallocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherallocation',
            unique_together={('teacher', 'subject', 'batch')},
        ),
    ]
