# Generated by Django 4.2.2 on 2024-04-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='location',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='teacherallocation',
            unique_together={('subject', 'batch')},
        ),
    ]
