# Generated by Django 4.2.2 on 2024-04-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_assignments_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='batch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.batch'),
        ),
    ]
