# Generated by Django 4.2.2 on 2024-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_assignments_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='batch',
        ),
        migrations.AddField(
            model_name='assignments',
            name='batch',
            field=models.ManyToManyField(default=1, to='users.batch'),
        ),
    ]
