# Generated by Django 4.2.2 on 2024-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_assignments_batch_assignments_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='batch',
            field=models.ManyToManyField(to='users.batch'),
        ),
    ]
