# Generated by Django 4.2.2 on 2024-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_assignments_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='location',
            field=models.FilePathField(blank=True, default='C:\\Users\\visha\\Desktop\\codingfiles\\pbl_project - Copy\\media'),
        ),
    ]
