# Generated by Django 4.2.2 on 2024-04-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_assignments_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='location',
        ),
    ]
