# Generated by Django 4.2.2 on 2024-04-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_student_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assignments',
        ),
    ]
