# Generated by Django 4.2.2 on 2024-04-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_assignments_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='batch',
        ),
        migrations.AddField(
            model_name='assignments',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.batch'),
        ),
    ]
