# Generated by Django 4.2.2 on 2024-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_assignmentsubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
