# Generated by Django 4.2.2 on 2024-04-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_assignmentsubmission_submission_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
