# Generated by Django 4.2.2 on 2024-04-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_assignmentsubmission_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student', 'subject')},
        ),
    ]
