# Generated by Django 4.2.2 on 2024-04-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_assignmentsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll_number',
            field=models.IntegerField(default='00000'),
        ),
    ]
