# Generated by Django 4.2.2 on 2024-04-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_customuser_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitted_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
