# Generated by Django 4.2.2 on 2024-04-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_assignmentsubmission_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
