# Generated by Django 4.2.2 on 2024-04-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_assignmentsubmission_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
