# Generated by Django 4.2.2 on 2024-04-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_assignmentsubmission_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_on',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
